### ISSUE TITLE
Editing submission throws a 500 error when adding a valid value

### ISSUE THREAD

**Issue by mdorf** [ncbo/bioportal_web_ui#408]
I added a valid URI in the Version IRI field and clicked Save:

![Image](https://github.com/user-attachments/assets/2398ca4f-2b87-4a0a-96cf-fce9a4558ae3)

This resulted in the following error in the API:

```
(API) >> Using HTTP Redis instance at ncbostage-redis2:6380
ArgumentError: wrong number of arguments (given 2, expected 1)
	/Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/models/ontology_submission.rb:242:in `URI='
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/solutions_mapper.rb:150:in `block (2 levels) in init_unloaded_attributes'
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/solutions_mapper.rb:136:in `each'
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/solutions_mapper.rb:136:in `block in init_unloaded_attributes'
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/solutions_mapper.rb:134:in `each'
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/solutions_mapper.rb:134:in `init_unloaded_attributes'
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/solutions_mapper.rb:104:in `map_each_solutions'
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/loader.rb:97:in `model_load_sliced'
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/loader.rb:30:in `model_load'
	/Users/mdorf/dev/ncbo/goo/lib/goo/sparql/queries.rb:55:in `model_load'
	/Users/mdorf/dev/ncbo/goo/lib/goo/base/where.rb:219:in `process_query_intl'
	/Users/mdorf/dev/ncbo/goo/lib/goo/base/where.rb:131:in `process_query'
	/Users/mdorf/dev/ncbo/goo/lib/goo/base/where.rb:287:in `all'
	/Users/mdorf/dev/ncbo/goo/lib/goo/base/resource.rb:192:in `bring'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/validator.rb:78:in `attr_value'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/implementations/distinct_of.rb:24:in `distinct?'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/implementations/distinct_of.rb:13:in `block in <class:DistinctOf>'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/validator.rb:13:in `instance_eval'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/validator.rb:13:in `valid?'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/enforce.rb:103:in `check'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/enforce.rb:47:in `block in enforce'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/enforce.rb:16:in `each'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/enforce.rb:16:in `enforce'
	/Users/mdorf/dev/ncbo/goo/lib/goo/validators/enforce.rb:129:in `enforce'
	/Users/mdorf/dev/ncbo/goo/lib/goo/base/resource.rb:44:in `block in valid?'
	/Users/mdorf/dev/ncbo/goo/lib/goo/base/resource.rb:42:in `each'
	/Users/mdorf/dev/ncbo/goo/lib/goo/base/resource.rb:42:in `valid?'
	/Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/models/ontology_submission.rb:303:in `valid?'
```

**Comment by syphax-bouazzouni** [comment]
you need to change that line to be `uri=`, in AgroPortal we have it in uppercase.

**Comment by syphax-bouazzouni** [comment]
Can you show me what are the 2 arguments given for that function?

**Comment by mdorf** [comment]
To add some detail, if I modify the original setter to accept 2 arguments, I get this result:
```
From: /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/models/ontology_submission.rb:244 LinkedData::Models::OntologySubmission#URI=:

    242: def URI=(value, on_load)
    243:
 => 244:   binding.pry
    245:
    246:   self.uri  = value
    247: end

[1] pry(#<LinkedData::Models::OntologySubmission>)> value
=> nil
[10] pry(#<LinkedData::Models::OntologySubmission>)> on_load
=> {:on_load=>true}
```

**Comment by syphax-bouazzouni** [comment]
OK, and what is the body that the UI is sending to the API ? it should not contain any key with named `URI`, instead  it should be`uri`

**Comment by mdorf** [comment]
> OK, and what is the body that the UI is sending to the API ? it should not contain any key with named `URI`, instead it should be`uri`

```
_method: put
authenticity_token: zlqMCd_4QVeRIjnI5zvhnZ2ki0wooDqIPxuedbgn9rmXz9ySXHQEqf1tq8HAV5pAbpzA038s6rKwRe-HrC2Rrw
ontology[acronym]: ECTO
ontology[name]: Environmental conditions, treatments and exposures ontology
submission[hasOntologyLanguage]: OWL
ontology[hasDomain][]: 
ontology[hasDomain][]: http://localhost:9393/categories/Other
ontology[group][]: 
ontology[group][]: http://localhost:9393/groups/OBO_Foundry
ontology[administeredBy][]: http://localhost:9393/users/vendetti
submission[contact][0][name]: Anne Thessen
submission[contact][0][email]: annethessen@gmail.com
submission[version]: 2023-02-14
submission[status]: production
submission[deprecated]: submission[deprecated]
submission[versionIRI]: http://www.yahoo222.com
submission[hasFormalityLevel]: 
submission[hasOntologySyntax]: 
submission[isOfType]: 
submission[identifier][0]: 
submission[uri]: http://purl.obolibrary.org/obo/ecto.owl
button: 
```

**Comment by syphax-bouazzouni** [comment]
it seems fine from UI

**Comment by mdorf** [comment]
Just to confirm, this error appears to happen specifically when editing the `versionIRI` field. If I edit the `uri` field and leave `versionIRI` blank, the error does not occur.

**Comment by syphax-bouazzouni** [comment]
Fixed in https://github.com/ontoportal/ontologies_linked_data/pull/21/commits/8bb09be9f41c1d6f3dd18fdb867b05339d6f1cc8

**Comment by mdorf** [comment]
Just for the record, this addresses the initial issue, but the 500 error still persists.

**Comment by mdorf** [comment]
resolved in https://github.com/ncbo/bioportal_web_ui/pull/413, https://github.com/ontoportal/ontoportal_web_ui/pull/42
